/*
* Copyright (c) 2007 Nokia Corporation and/or its subsidiary(-ies). 
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Helper class for wait notes
*
*/


//The coding convention for enums has not been followed
//because this will require to change in almost all the places
//401-1815 Ease of Instant Messaging branding
//Code added for the above requirment
//Any new feature/variation flags to be added at the end also the same
//to the CAVariation.rss at the end.
//Please be carefull before editing any of these variations..


#ifndef _VARIATNKEYS_H_
#define _VARIATNKEYS_H_


#include    "IMPrivateCRKeys.h"


// Variant Keys.h
typedef enum KeyTableIndex
    {
    RSC_CHAT_VARIATION_SCREENNAME_QUERY = 1,
    RSC_CHAT_VARIATION_SCREENNAME_DEFAULT,
    RSC_CHAT_VARIATION_SCREENNAME_SETTING,
    RSC_CHAT_VARIATION_HAVEGRANT,
    RSC_CHAT_VARIATION_MODIFY_CONTACT_LIST,
    RSC_CHAT_VARIATION_HIDE_WV,
    RSC_CHAT_VARIATION_FETCH_PRESENCE,
    RSC_CHAT_VARIATION_HAVEPRESENCEAUTH,
    RSC_CHAT_VARIATION_SEND_MSG_IGNORE_OFFLINE,
    RSC_CHAT_VARIATION_ALWAYSONLINE_AFTER_FIRST_LOGIN,
    RSC_CHAT_VARIATION_HAVE_ALIAS,
    RSC_CHAT_VARIATION_ALIAS_MANDATORY,
    RSC_CHAT_VARIATION_MSISDN_SUPPORT,
    RSC_CHAT_VARIATION_ALLOW_EDIT_GROUP_PROPERTIES,
    RSC_CHAT_VARIATION_SIMPLE_GROUP_CREATION,
    RSC_CHAT_VARIATION_LOCAL_ECHO_USED_IN_GROUP,
    RSC_CHAT_VARIATION_OWN_MSG_ICON,
    RSC_CHAT_VARIATION_MSG_ICON,
    RSC_CHAT_VARIATION_REACTIVE_PRESENCE_AUTH,
    RSC_CHAT_VARIATION_USERID_TEXTUAL_INPUTMODE,
    RSC_CHAT_VARIATION_HAVE_NICKNAME,
    RSC_CHAT_VARIATION_SEARCH_NAME,
    RSC_CHAT_VARIATION_SEARCH_USERID,
    RSC_CHAT_VARIATION_SEARCH_PHONE,
    RSC_CHAT_VARIATION_SEARCH_EMAIL,
    RSC_CHAT_VARIATION_SEARCH_GROUPNAME,
    RSC_CHAT_VARIATION_SEARCH_GROUPTOPIC,
    RSC_CHAT_VARIATION_SEARCH_GROUPMEMBER,
    RSC_CHAT_VARIATION_SEND_MSG_IGNORE_OFFLINE_NOTIFY,
    RSC_CHAT_VARIATION_AUTOMATIC_STATUS_CHANGE,
    RSC_CHAT_VARIATION_WELCOME_NOTE,
    RSC_CHAT_VARIATION_BLOCKING,
    RSC_CHAT_VARIATION_GROUP_TOPIC,
    RSC_CHAT_VARIATION_GROUP_WELCOME_NOTE,
    RSC_CHAT_VARIATION_GROUP_SIZE,
    RSC_CHAT_VARIATION_GROUP_WHISPER,
    RSC_CHAT_VARIATION_GROUP_SEARCH,
    RSC_CHAT_VARIATION_GROUP_OPEN,
    RSC_CHAT_VARIATION_SEND_IMAGE,
    RSC_CHAT_VARIATION_JOIN_CHAT_ROOM_MANUAL,
    RSC_CHAT_VARIATION_GROUP_AUTODELETE,
    RSC_CHAT_VARIATION_UNEDITABLE_USERID,
    RSC_CHAT_VARIATION_APPEAR_OFFLINE,
    RSC_CHAT_VARIATION_SAVE_PW_QUERY,
    RSC_CHAT_VARIATION_APP_LAUNCH_QUERY,
    RSC_CHAT_VARIATION_RCPT_BLOCKED_NOTE,
    RSC_CHAT_VARIATION_DOMAIN_SELECTION,
    RSC_CHAT_VARIATION_UPDATE_CONTACTS_SETTING,
    RSC_CHAT_VARIATION_DEVICE_TYPE_TO_ONLINE_STATUS,
    RSC_CHAT_VARIATION_BUSY_STATUS,
    RSC_CHAT_VARIATION_SHOW_BLOCKED_LIST,
    RSC_CHAT_VARIATION_RECORD_WARNING,
    RSC_CHAT_VARIATION_SAVE_PW_WARNING,
    RSC_CHAT_VARIATION_AWAY_STATUS,
    RSC_CHAT_VARIATION_CREATE_DELETE_CONTACT_LIST,
    RSC_CHAT_VARIATION_ONLINE_AUTO,
    RSC_CHAT_VARIATION_AWAY_AUTO,
    RSC_CHAT_VARIATION_BUSY_AUTO,
    RSC_CHAT_VARIATION_ONLINE_OPTION,
    RSC_CHAT_VARIATION_AWAY_OPTION,
    RSC_CHAT_VARIATION_BUSY_OPTION,
    RSC_CHAT_VARIATION_HIDE_ONLY_PREFIX,
    RSC_CHAT_VARIATION_BLOCK_QUERY,
    RSC_CHAT_VARIATION_CONTACT_LISTS_CAPITALIZED,
    RSC_CHAT_VARIATION_OVERRIDE_DEFAULT_TONE,
    RSC_CHAT_VARIATION_MESSAGE_MAX_LENGTH,
    RSC_CHAT_VARIATION_SHOW_USER_IDENTITY,
    RSC_CHAT_VARIATION_SHOW_SPLASH_SCREEN,
    RSC_CHAT_VARIATION_SPLASH_SCREEN_DURATION,
    RSC_CHAT_VARIATION_SHOW_TEMPLATES
    } KeyTableIndex;


#endif

//End of File